### PR TITLE
Update 6.2.4

### PR DESCRIPTION
**Pull request by gcaguilar**

### CODE REVIEW

**Comment by ghisvail** [comment]
Thank you for proposing this update. Please consider rebasing your changes on top of the current `master` to make the history a bit less crowded. Also, please squash c358653 and 8b2a081 together to a single `Update 6.2.4` commit to stay consistent with past updates.

Cheers,

**Comment by gcaguilar** [comment]
Okay, is that right?

**Comment by ghisvail** [comment]
@gcaguilar Would you prefer me to do it?

**Comment by gcaguilar** [comment]
@ghisvail That would be great, thank you.

**Comment by ghisvail** [comment]
Superseded by #9. I cherry-picked your commit as is.

Thanks for your contribution.

**Pull request closed without merging**
